axon:
  axonserver:
    client-id: emitter
  serializer:
    events: jackson
  kafka:
    publisher:
      enabled: true
    clientid: axon-emitter
    producer:
      event-processor-mode: tracking
      retries: 0
      bootstrap-servers: redpanda:29092
      value-serializer: io.cloudevents.kafka.CloudEventSerializer
    consumer:
      bootstrap-servers: redpanda:29092
      value-deserializer: io.cloudevents.kafka.CloudEventDeserializer
    properties:
      security.protocol: PLAINTEXT
    message-converter-mode: cloud_event
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
server:
  port: 8333